export default {
	lunbodatas:[
		{
			img:'./assets/image/2017/3/bz1.jpg',
			href:'#'
		},
		{
			img:'./assets/image/2017/3/bz2.jpg',
			href:'#'
		},
		{
			img:'./assets/image/2017/3/bz3.jpg',
			href:'#'
		},
		{
			img:'./assets/image/2017/3/bz4.jpg',
			href:'#'
		},
	],
	btndatas:[
		{
			img:'./assets/image/2017/3/btn1.jpg',
			href:'#'
		},
		{
			img:'./assets/image/2017/3/btn2.jpg',
			href:'#'
		},
		{
			img:'./assets/image/2017/3/btn3.jpg',
			href:'#'
		},
		{
			img:'./assets/image/2017/3/btn4.jpg',
			href:'#'
		},
		{
			img:'./assets/image/2017/3/btn5.jpg',
			href:'#'
		}
	],
	bannerdatas:[
		{
			img:'./assets/image/2017/3/banner1.jpg',
			href:'#'
		},
		{
			img:'./assets/image/2017/3/banner2.jpg',
			href:'#'
		}
	],
	lanmu_datas:{
		miaosha:{
			name:'miaosha',
			title:{
				title_left:'秒杀',
				title_right:'',
				iconshow:false,
				othercomponent:'miaosha'
		},
		content:[
			{
				img:'./assets/image/2017/3/other1.jpg',
				title:'$1',
				href:'#'
			},
			{
				img:'./assets/image/2017/3/other2.jpg',
				title:'$2',
				href:'#'
			},
			{
				img:'./assets/image/2017/3/other3.jpg',
				title:'$3',
				href:'#'
			}
		]
	},
	zhutiguan:{
		name:'zhutiguan',
		title:{
			title_left:'主题馆',
			title_right:'更多',
			iconshow:true
		},
		content:[
			{
				img:'./assets/image/2017/3/other1.jpg',
				title0:'图书',
				title1:'30万图书满100-50',
				href:'#'
			},
			{
				img:'./assets/image/2017/3/other1.jpg',
				title0:'电子书',
				title1:'vip免费畅读',
				href:'#'
			},
			{
				img:'./assets/image/2017/3/other1.jpg',
				title0:'网络文学',
				title1:'免费畅读不停歇',
				href:'#'
			},
			{
				img:'./assets/image/2017/3/other1.jpg',
				title0:'创意文具',
				title1:'本子 字帖 本册',
				href:'#'
			},
			{
				img:'./assets/image/2017/3/other1.jpg',
				title0:'0-2岁馆',
				title1:'婴儿书 婴儿装 婴儿用品',
				href:'#'
			},
			{
				img:'./assets/image/2017/3/other1.jpg',
				title0:'3-6岁馆',
				title1:'绘本 儿童科普 童装童鞋玩具',
				href:'#'
			}
		]
	},
	shangou:{
		name:'shangou',
		title:{
			title_left:'尾品汇·闪购',
			title_right:'更多',
			iconshow:true
		},
		content:[
			{
				img:'./assets/image/2017/3/shangou1.jpg',
				title0:'贝康馨童装',
				title1:'童装出游尾品汇',
				href:'#'
			},
			{
				img:'./assets/image/2017/3/shangou1.jpg',
				title0:'海贝超级品牌',
				title1:'满399减200',
				href:'#'
			},
			{
				img:'./assets/image/2017/3/shangou1.jpg',
				title0:'海贝超级品牌',
				title1:'满399减200',
				href:'#'
			},
			{
				img:'./assets/image/2017/3/shangou2.png',
				title0:'图书尾品汇',
				title1:'2.5折抢购',
				href:'#'
			}
			,
			{
				img:'./assets/image/2017/3/shangou2.png',
				title0:'图书尾品汇',
				title1:'2.5折抢购',
				href:'#'
			}
			,
			{
				img:'./assets/image/2017/3/shangou2.png',
				title0:'图书尾品汇',
				title1:'2.5折抢购',
				href:'#'
			}
		]
	}
}
}
